version: "2"
services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
      - "27017:27017"
